### ISSUE TITLE
Crackles with Meridian Explorer USB DAC

### ISSUE THREAD

**Issue by asktoby** [atoomic/moodeaudio#1]
I've just built Moode Audio on a Raspberry Pi.
When I connect a Meridian Explorer USB DAC I get occasional crackles.

If I swap the Meridian Explorer for a Creative XFi Pro the crackles are
gone.

If I install mpg123 on MoodeAudio and use that to play, I get the same
crackles.
If I use mpg123 on a fresh install of Raspbian I get the same crackles.
I've previously found the same issue with Volumio.

So it seems there is an issue with the underlying Raspbian support of the
Meridian Explorer?

Here is a link to my system info output from Moode Audio:
https://pastebin.com/bN4kz4QM

**Comment by asktoby** [comment]
Looks like it could be a duplicate of
https://github.com/raspberrypi/linux/issues/2215

**Comment by atoomic** [comment]
FYI, most moode audio issues are discussed here, be sure to use the last version of moode audio which seems to be at this day "4.12 (beta)"
 
http://www.diyaudio.com/forums/pc-based/271811-moode-audio-player-raspberry-pi-1260.html?s=201c9ba0abeb6ebd70cb19c9b17cc928

I do not maintain mood audio, this is just a fork/repo I created to be able to track my own patches.

**Comment by asktoby** [comment]
A 1260-page thread for bug reporting??! No thank you!
