### ISSUE TITLE
Please, what's the default ssh account/password ?

### ISSUE THREAD

**Issue by laymonk** [atoomic/moodeaudio#2]
Hello,

I just setup moodeaudio on a raspberry-pi .. 

I then used the WebUI to enable ssh, but now my old account/password no longer logs me in.  

The [readme.txt](https://github.com/atoomic/moodeaudio/blob/master/readme.txt) suggests pi/raspberry as default username/password but that doesn't work either.

I have tried from both the web ssh console and a desktop ssh session.

Please, what is the default ssh username/password?

Thanks

**Comment by atoomic** [comment]
can you try user moode and password moodeaudio

**Comment by laymonk** [comment]
Thanks for responding, @atoomic  .. 

But moode/moodeaudio has not worked .. I am trying this from a physically attached monitor/keyboard .. 
(no longer able to do ssh, because I moved the unit and need to reconfigure the network before I can use ssh) .. 

On another note, it was frustrating trying to prepare the unit for a network move, because the netmask field is a dropdown and the dropdown options offered nothing that matched my netmask .. 

So, really, I think the netmask field should be a normal field, instead of a dropdown ..

**Comment by atoomic** [comment]
Ok what version of moode audio are you using?
I just checked on mine, which is a little old:
```
moode audio version 1.1
user: pi
password: raspberry
```

**Comment by laymonk** [comment]
Thanks again, atoomic .. I already tried that and it didn't work .. 

I have had to mount the sdcard and sort it out that way .. so, that's no longer an issue .. 

* Forgot to add:  I am on the latest version.  System info on the webUI cannot confirm the version I have, and I haven't figured out a CLI way to tell what version of moodeaudio is installed.

I have another issue though, which is how to choose the sound driver (for bcm2835_i2s)  .. for a Raspberry Pi 1 B .. There is no information I can see anywhere om how to match the sound device to one of the i2s drivers [listed here](http://moodeaudio.org/docs/devices.html) .. 

Should this be a trial-by-error thing ? 

Any suggestions ?  Thanks

**Comment by laymonk** [comment]
@atoomic, I have resolved my issues with sound .. please, feel free to close this .. 

I had assumed that a sound device was working, but it seemed dead on the hardware .. I switched to the base PCM / ALSA on-boad basic sound device (and disabled i2s), and now moode is working .. 

On the whole, it would be great to get together a little wiki pointing people to resources for understanding the sound devices available and how to choose drivers .. 

I can help with some wiki entries .. how best can I do this? Fork, and pull-request ?

**Comment by atoomic** [comment]
Thanks for your feedback, feel free to fork and add some pull request with some wiki/doc entries
